### PR TITLE
[RFC] feat(ci): add ubuntu-24.04 to build matrix

### PR DESCRIPTION
**Pull request by GoetzGoerisch**
* extend static code analysis with clang-15 and clang-18 on the different ubuntu variants

Remark: failing clang build jobs relate to a clang error possibly introduced with https://github.com/open62541/open62541/commit/9260330fac34aceb6c110b2dfb7550bdb23f4702
at https://github.com/open62541/open62541/blob/b34233b07c80dea87c849fb3295b958c55fe1f27/tests/pubsub/check_pubsub_connection_ethernet.c#L223

unrelated to this PR.

### CODE REVIEW

**Comment by jpfr** [comment]
Please rebase on master after #6851.

**Comment by GoetzGoerisch** [comment]
Thx @jpfr ,

How to handle the remaining clang warnings in `Build & Unit Tests (clang-18)`
```
/home/runner/work/open62541/open62541/deps/nodesetLoader/backends/open62541/src/DataTypeImporter.c:85:16: error: defining a type within 'offsetof' is a Clang extension [-Werror,-Wgnu-offsetof-extensions]
   85 |         return alignof(UA_Boolean);
      |                ^~~~~~~~~~~~~~~~~~~
/home/runner/work/open62541/open62541/deps/nodesetLoader/backends/open62541/src/DataTypeImporter.c:20:9: note: expanded from macro 'alignof'
   20 |         struct {                                                               \
      |         ^~~~~~
/usr/lib/llvm-18/lib/clang/18/include/__stddef_offsetof.h:16:43: note: expanded from macro 'offsetof'
   16 | #define offsetof(t, d) __builtin_offsetof(t, d)
      |                                           ^
/home/runner/work/open62541/open62541/deps/nodesetLoader/backends/open62541/src/DataTypeImporter.c:87:16: error: defining a type within 'offsetof' is a Clang extension [-Werror,-Wgnu-offsetof-extensions]
   87 |         return alignof(UA_SByte);
      |                ^~~~~~~~~~~~~~~~~
/home/runner/work/open62541/open62541/deps/nodesetLoader/backends/open62541/src/DataTypeImporter.c:20:9: note: expanded from macro 'alignof'
   20 |         struct {                                                               \
      |         ^~~~~~
/usr/lib/llvm-18/lib/clang/18/include/__stddef_offsetof.h:16:43: note: expanded from macro 'offsetof'
   16 | #define offsetof(t, d) __builtin_offsetof(t, d)
      |                                           ^
/home/runner/work/open62541/open62541/deps/nodesetLoader/backends/open62541/src/DataTypeImporter.c:89:16: error: defining a type within 'offsetof' is a Clang extension [-Werror,-Wgnu-offsetof-extensions]
   89 |         return alignof(UA_Byte);
      |                ^~~~~~~~~~~~~~~~
/home/runner/work/open62541/open62541/deps/nodesetLoader/backends/open62541/src/DataTypeImporter.c:20:9: note: expanded from macro 'alignof'
   20 |         struct {                                                               \
      |         ^~~~~~
/usr/lib/llvm-18/lib/clang/18/include/__stddef_offsetof.h:16:43: note: expanded from macro 'offsetof'
   16 | #define offsetof(t, d) __builtin_offsetof(t, d)
      |                                           ^
/home/runner/work/open62541/open62541/deps/nodesetLoader/backends/open62541/src/DataTypeImporter.c:91:16: error: defining a type within 'offsetof' is a Clang extension [-Werror,-Wgnu-offsetof-extensions]
   91 |         return alignof(UA_Int16);
      |                ^~~~~~~~~~~~~~~~~
/home/runner/work/open62541/open62541/deps/nodesetLoader/backends/open62541/src/DataTypeImporter.c:20:9: note: expanded from macro 'alignof'
   20 |         struct {                                                               \
      |         ^~~~~~
/usr/lib/llvm-18/lib/clang/18/include/__stddef_offsetof.h:16:43: note: expanded from macro 'offsetof'
   16 | #define offsetof(t, d) __builtin_offsetof(t, d)
      |                                           ^
/home/runner/work/open62541/open62541/deps/nodesetLoader/backends/open62541/src/DataTypeImporter.c:93:16: error: defining a type within 'offsetof' is a Clang extension [-Werror,-Wgnu-offsetof-extensions]
   93 |         return alignof(UA_UInt16);
      |                ^~~~~~~~~~~~~~~~~~
/home/runner/work/open62541/open62541/deps/nodesetLoader/backends/open62541/src/DataTypeImporter.c:20:9: note: expanded from macro 'alignof'
   20 |         struct {                                                               \
      |         ^~~~~~
/usr/lib/llvm-18/lib/clang/18/include/__stddef_offsetof.h:16:43: note: expanded from macro 'offsetof'
   16 | #define offsetof(t, d) __builtin_offsetof(t, d)
      |                                           ^
/home/runner/work/open62541/open62541/deps/nodesetLoader/backends/open62541/src/DataTypeImporter.c:95:16: error: defining a type within 'offsetof' is a Clang extension [-Werror,-Wgnu-offsetof-extensions]
   95 |         return alignof(UA_Int32);
      |                ^~~~~~~~~~~~~~~~~
/home/runner/work/open62541/open62541/deps/nodesetLoader/backends/open62541/src/DataTypeImporter.c:20:9: note: expanded from macro 'alignof'
   20 |         struct {                                                               \
      |         ^~~~~~
/usr/lib/llvm-18/lib/clang/18/include/__stddef_offsetof.h:16:43: note: expanded from macro 'offsetof'
   16 | #define offsetof(t, d) __builtin_offsetof(t, d)
      |                                           ^
/home/runner/work/open62541/open62541/deps/nodesetLoader/backends/open62541/src/DataTypeImporter.c:97:16: error: defining a type within 'offsetof' is a Clang extension [-Werror,-Wgnu-offsetof-extensions]
   97 |         return alignof(UA_UInt32);
      |                ^~~~~~~~~~~~~~~~~~
/home/runner/work/open62541/open62541/deps/nodesetLoader/backends/open62541/src/DataTypeImporter.c:20:9: note: expanded from macro 'alignof'
   20 |         struct {                                                               \
      |         ^~~~~~
/usr/lib/llvm-18/lib/clang/18/include/__stddef_offsetof.h:16:43: note: expanded from macro 'offsetof'
   16 | #define offsetof(t, d) __builtin_offsetof(t, d)
      |                                           ^
/home/runner/work/open62541/open62541/deps/nodesetLoader/backends/open62541/src/DataTypeImporter.c:99:16: error: defining a type within 'offsetof' is a Clang extension [-Werror,-Wgnu-offsetof-extensions]
   99 |         return alignof(UA_Int64);
      |                ^~~~~~~~~~~~~~~~~
/home/runner/work/open62541/open62541/deps/nodesetLoader/backends/open62541/src/DataTypeImporter.c:20:9: note: expanded from macro 'alignof'
   20 |         struct {                                                               \
      |         ^~~~~~
/usr/lib/llvm-18/lib/clang/18/include/__stddef_offsetof.h:16:43: note: expanded from macro 'offsetof'
   16 | #define offsetof(t, d) __builtin_offsetof(t, d)
      |                                           ^
/home/runner/work/open62541/open62541/deps/nodesetLoader/backends/open62541/src/DataTypeImporter.c:101:16: error: defining a type within 'offsetof' is a Clang extension [-Werror,-Wgnu-offsetof-extensions]
  101 |         return alignof(UA_UInt64);
      |                ^~~~~~~~~~~~~~~~~~
/home/runner/work/open62541/open62541/deps/nodesetLoader/backends/open62541/src/DataTypeImporter.c:20:9: note: expanded from macro 'alignof'
   20 |         struct {                                                               \
      |         ^~~~~~
/usr/lib/llvm-18/lib/clang/18/include/__stddef_offsetof.h:16:43: note: expanded from macro 'offsetof'
   16 | #define offsetof(t, d) __builtin_offsetof(t, d)
      |                                           ^
/home/runner/work/open62541/open62541/deps/nodesetLoader/backends/open62541/src/DataTypeImporter.c:103:16: error: defining a type within 'offsetof' is a Clang extension [-Werror,-Wgnu-offsetof-extensions]
  103 |         return alignof(UA_Float);
      |                ^~~~~~~~~~~~~~~~~
/home/runner/work/open62541/open62541/deps/nodesetLoader/backends/open62541/src/DataTypeImporter.c:20:9: note: expanded from macro 'alignof'
   20 |         struct {                                                               \
      |         ^~~~~~
/usr/lib/llvm-18/lib/clang/18/include/__stddef_offsetof.h:16:43: note: expanded from macro 'offsetof'
   16 | #define offsetof(t, d) __builtin_offsetof(t, d)
      |                                           ^
/home/runner/work/open62541/open62541/deps/nodesetLoader/backends/open62541/src/DataTypeImporter.c:105:16: error: defining a type within 'offsetof' is a Clang extension [-Werror,-Wgnu-offsetof-extensions]
  105 |         return alignof(UA_Double);
      |                ^~~~~~~~~~~~~~~~~~
/home/runner/work/open62541/open62541/deps/nodesetLoader/backends/open62541/src/DataTypeImporter.c:20:9: note: expanded from macro 'alignof'
   20 |         struct {                                                               \
      |         ^~~~~~
/usr/lib/llvm-18/lib/clang/18/include/__stddef_offsetof.h:16:43: note: expanded from macro 'offsetof'
   16 | #define offsetof(t, d) __builtin_offsetof(t, d)
      |                                           ^
/home/runner/work/open62541/open62541/deps/nodesetLoader/backends/open62541/src/DataTypeImporter.c:107:16: error: defining a type within 'offsetof' is a Clang extension [-Werror,-Wgnu-offsetof-extensions]
  107 |         return alignof(UA_QualifiedName);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/open62541/open62541/deps/nodesetLoader/backends/open62541/src/DataTypeImporter.c:20:9: note: expanded from macro 'alignof'
   20 |         struct {                                                               \
      |         ^~~~~~
/usr/lib/llvm-18/lib/clang/18/include/__stddef_offsetof.h:16:43: note: expanded from macro 'offsetof'
   16 | #define offsetof(t, d) __builtin_offsetof(t, d)
      |                                           ^
/home/runner/work/open62541/open62541/deps/nodesetLoader/backends/open62541/src/DataTypeImporter.c:109:16: error: defining a type within 'offsetof' is a Clang extension [-Werror,-Wgnu-offsetof-extensions]
  109 |         return alignof(UA_LocalizedText);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/open62541/open62541/deps/nodesetLoader/backends/open62541/src/DataTypeImporter.c:20:9: note: expanded from macro 'alignof'
   20 |         struct {                                                               \
      |         ^~~~~~
/usr/lib/llvm-18/lib/clang/18/include/__stddef_offsetof.h:16:43: note: expanded from macro 'offsetof'
   16 | #define offsetof(t, d) __builtin_offsetof(t, d)
      |                                           ^
/home/runner/work/open62541/open62541/deps/nodesetLoader/backends/open62541/src/DataTypeImporter.c:111:16: error: defining a type within 'offsetof' is a Clang extension [-Werror,-Wgnu-offsetof-extensions]
  111 |         return alignof(UA_StatusCode);
      |                ^~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/open62541/open62541/deps/nodesetLoader/backends/open62541/src/DataTypeImporter.c:20:9: note: expanded from macro 'alignof'
   20 |         struct {                                                               \
      |         ^~~~~~
/usr/lib/llvm-18/lib/clang/18/include/__stddef_offsetof.h:16:43: note: expanded from macro 'offsetof'
   16 | #define offsetof(t, d) __builtin_offsetof(t, d)
      |                                           ^
/home/runner/work/open62541/open62541/deps/nodesetLoader/backends/open62541/src/DataTypeImporter.c:113:16: error: defining a type within 'offsetof' is a Clang extension [-Werror,-Wgnu-offsetof-extensions]
  113 |         return alignof(UA_String);
      |                ^~~~~~~~~~~~~~~~~~
/home/runner/work/open62541/open62541/deps/nodesetLoader/backends/open62541/src/DataTypeImporter.c:20:9: note: expanded from macro 'alignof'
   20 |         struct {                                                               \
      |         ^~~~~~
/usr/lib/llvm-18/lib/clang/18/include/__stddef_offsetof.h:16:43: note: expanded from macro 'offsetof'
   16 | #define offsetof(t, d) __builtin_offsetof(t, d)
      |                                           ^
/home/runner/work/open62541/open62541/deps/nodesetLoader/backends/open62541/src/DataTypeImporter.c:115:16: error: defining a type within 'offsetof' is a Clang extension [-Werror,-Wgnu-offsetof-extensions]
  115 |         return alignof(UA_ByteString);
      |                ^~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/open62541/open62541/deps/nodesetLoader/backends/open62541/src/DataTypeImporter.c:20:9: note: expanded from macro 'alignof'
   20 |         struct {                                                               \
      |         ^~~~~~
/usr/lib/llvm-18/lib/clang/18/include/__stddef_offsetof.h:16:43: note: expanded from macro 'offsetof'
   16 | #define offsetof(t, d) __builtin_offsetof(t, d)
      |                                           ^
/home/runner/work/open62541/open62541/deps/nodesetLoader/backends/open62541/src/DataTypeImporter.c:117:16: error: defining a type within 'offsetof' is a Clang extension [-Werror,-Wgnu-offsetof-extensions]
  117 |         return alignof(UA_DateTime);
      |                ^~~~~~~~~~~~~~~~~~~~
/home/runner/work/open62541/open62541/deps/nodesetLoader/backends/open62541/src/DataTypeImporter.c:20:9: note: expanded from macro 'alignof'
   20 |         struct {                                                               \
      |         ^~~~~~
/usr/lib/llvm-18/lib/clang/18/include/__stddef_offsetof.h:16:43: note: expanded from macro 'offsetof'
   16 | #define offsetof(t, d) __builtin_offsetof(t, d)
      |                                           ^
/home/runner/work/open62541/open62541/deps/nodesetLoader/backends/open62541/src/DataTypeImporter.c:119:16: error: defining a type within 'offsetof' is a Clang extension [-Werror,-Wgnu-offsetof-extensions]
  119 |         return alignof(UA_ExpandedNodeId);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/open62541/open62541/deps/nodesetLoader/backends/open62541/src/DataTypeImporter.c:20:9: note: expanded from macro 'alignof'
   20 |         struct {                                                               \
      |         ^~~~~~
/usr/lib/llvm-18/lib/clang/18/include/__stddef_offsetof.h:16:43: note: expanded from macro 'offsetof'
   16 | #define offsetof(t, d) __builtin_offsetof(t, d)
      |                                           ^
/home/runner/work/open62541/open62541/deps/nodesetLoader/backends/open62541/src/DataTypeImporter.c:121:16: error: defining a type within 'offsetof' is a Clang extension [-Werror,-Wgnu-offsetof-extensions]
  121 |         return alignof(UA_NodeId);
      |                ^~~~~~~~~~~~~~~~~~
/home/runner/work/open62541/open62541/deps/nodesetLoader/backends/open62541/src/DataTypeImporter.c:20:9: note: expanded from macro 'alignof'
   20 |         struct {                                                               \
      |         ^~~~~~
/usr/lib/llvm-18/lib/clang/18/include/__stddef_offsetof.h:16:43: note: expanded from macro 'offsetof'
   16 | #define offsetof(t, d) __builtin_offsetof(t, d)
      |                                           ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
```

**Comment by jpfr** [comment]
idk.
Maybe we need to get rid of the alignof macro.
The problem seems to be that use typedef on 
“Anonymous” structs.

such as typedef struct { } typename;

**Comment by GoetzGoerisch** [comment]
requires https://github.com/open62541/open62541-nodeset-loader/pull/263 to be merged first

**Comment by GoetzGoerisch** [comment]
@jpfr please review the nodesetLoader PR mentioned above and merge if possible.

Please also review this PR, the failing TPM build will be fixed.

After the nodesetLoader is merged I would like to revisit this one and maybe we need to adjust the submodule commit.

Please let me know any further things you like to improve or update.

**Comment by jpfr** [comment]
@GoetzGoerisch done

You can update the git submodule as part of this PR.

**Comment by jpfr** [comment]
Top, merged.

**Comment by GoetzGoerisch** [comment]
@jpfr the 24.04 Build all CS fails from time to time.

As the generated code sometimes fails with:

```
[ 80%] Building C object tools/nodeset_injector/CMakeFiles/autoinject_library.dir/__/__/src_generated/open62541/nodesetinjector.c.o
/home/runner/work/open62541/open62541/build/src_generated/open62541/nodesetinjector.c:3:8: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘|=’ token
    3 | retval |= namespace_autoid_generated(server);
      |        ^~
/home/runner/work/open62541/open62541/build/src_generated/open62541/nodesetinjector.c:4:1: error: expected identifier or ‘(’ before ‘if’
    4 | if(retval != UA_STATUSCODE_GOOD) {
      | ^~
/home/runner/work/open62541/open62541/build/src_generated/open62541/nodesetinjector.c:9:50: error: expected ‘)’ before string constant
    9 | UA_LOG_INFO(UA_Log_Stdout, UA_LOGCATEGORY_SERVER, "The namespace_autoid_generated successfully added.");
      |                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                  )
cc1: note: unrecognized command-line option ‘-Wno-static-in-inline’ may have been intended to silence earlier diagnostics
make[3]: *** [tools/nodeset_injector/CMakeFiles/autoinject_library.dir/build.make:1249: tools/nodeset_injector/CMakeFiles/autoinject_library.dir/__/__/src_generated/open62541/nodesetinjector.c.o] Error 1
```

Locally I have not been able to reproduce this.
