### ISSUE TITLE
Build on 1.4 branch requires Linux header files

### ISSUE THREAD

**Issue by sgoll** [open62541/open62541#6360]
## Description

The dev version on the 1.4 branch does not compile anymore with musl instead of GNU libc. The 1.3 branch still compiles without error, so this seems like a regression.

```text
/open62541/arch/eventloop_posix_eth.c:18:10: fatal error: linux/if_packet.h: No such file or directory
   18 | #include <linux/if_packet.h>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/open62541-plugins.dir/build.make:418: CMakeFiles/open62541-plugins.dir/arch/eventloop_posix_eth.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:301: CMakeFiles/open62541-plugins.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

## Background Information / Reproduction Steps

Used CMake options: (none)

The issue can be reproduced with the following `Dockerfile` using the [Alpine Linux](https://hub.docker.com/_/alpine) distribution:[^1]

[^1]: It is sufficient to run the Docker build like so: `docker build -t test .`

```docker
FROM alpine:3.19
RUN apk add --no-cache alpine-sdk cmake python3
WORKDIR /
RUN git clone https://github.com/open62541/open62541.git -b 1.4
WORKDIR /open62541
RUN mkdir build && cd build && cmake ..
WORKDIR /open62541/build
RUN make
```

If `-b 1.4` is replaced with `-b 1.3`, the build finishes successfully without compilation errors.

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): branch `1.4`, commit 665d328aa67e20fe1e3eabcf1f789d554c8c9604
 - [ ] Other OPC UA SDKs used (client or server): (none)
 - [x] Operating system: Alpine Linux
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [x] Self-contained code example attached
 - [ ] Critical issue
