### ISSUE TITLE
Shared Library Build Error with OpenSSL 1.1.1n

### ISSUE THREAD

**Issue by ffreality** [open62541/open62541#5818]
## Description
Shared library build with OpenSSL 1.1.1n on Windows gives these errors on Visual Studio 2022.
```
11>libcrypto.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp_CertOpenStore referenced in function capi_open_store
11>libcrypto.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp_CertCloseStore referenced in function capi_find_key
11>libcrypto.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp_CertEnumCertificatesInStore referenced in function capi_find_cert
11>libcrypto.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp_CertFindCertificateInStore referenced in function capi_find_cert
11>libcrypto.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp_CertDuplicateCertificateContext referenced in function capi_load_ssl_client_cert
11>libcrypto.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp_CertFreeCertificateContext referenced in function capi_dsa_free
11>libcrypto.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp_CertGetCertificateContextProperty referenced in function capi_cert_get_fname
11>E:\Github\C++\OPCUA\open62541\builds\OpenSSL_Dynamic\bin\Release\open62541.dll : fatal error LNK1120: 7 unresolved externals
```
I find this issue on OpenSSL repo but I don't know how can I integrate crypt32.lib
https://github.com/openssl/openssl/issues/1061

I can't change OpenSSL verison because it comes from Unreal Engine and this problem is related with my `Unreal Engine` plugin. (I got error on open62's build. Not Unreal's package builds. But if I use another version, it will give library clash error.)

Static library build with `amalgamation` works and I can use it with Unreal Engine but dynamic library is better for license.

Used CMake options:

```
UA_ENABLE_ENCRYPTION:STRING=OPENSSL
UA_ENABLE_PUBSUB_DELTAFRAMES:BOOL=1
UA_ENABLE_PUBSUB:BOOL=1
SSL_EAY_RELEASE:FILEPATH=E:/Epic/Engines/UE_5.2/Engine/Source/ThirdParty/OpenSSL/1.1.1n/lib/Win64/VS2015/Release/libssl.lib
UA_ENABLE_PUBSUB_INFORMATIONMODEL:BOOL=1
SSL_EAY_DEBUG:FILEPATH=SSL_EAY_DEBUG-NOTFOUND
UA_ENABLE_PUBSUB_INFORMATIONMODEL_METHODS:BOOL=1
CMAKE_BUILD_TYPE:STRING=Release
UA_ENABLE_DISCOVERY:BOOL=1
BUILD_SHARED_LIBS:BOOL=1
OPENSSL_INCLUDE_DIR:PATH=E:/Epic/Engines/UE_5.2/Engine/Source/ThirdParty/OpenSSL/1.1.1n/include/Win64/VS2015
UA_ENABLE_HISTORIZING:BOOL=1
UA_NAMESPACE_ZERO:STRING=FULL
LIB_EAY_DEBUG:FILEPATH=LIB_EAY_DEBUG-NOTFOUND
LIB_EAY_RELEASE:FILEPATH=E:/Epic/Engines/UE_5.2/Engine/Source/ThirdParty/OpenSSL/1.1.1n/lib/Win64/VS2015/Release/libcrypto.lib
```

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): Master (commit number 0b1d72f - 18 Hours Ago)
 - [x] Operating system: Windows 11
 - [x] Critical issue
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
