### ISSUE TITLE
Werror=deprecated-declarations since openSSL 3.0 

### ISSUE THREAD

**Issue by Boberic1999** [open62541/open62541#5295]
## Description
I'm trying to write a server with OPENSSL encryption (x509 certificates). I would use UaExpert as client. After enabling openSSL encryption, and building, im getting output in ubuntu 22.04 terminal :

/home/marko/Desktop/open62541_8_8_2022/open62541/build/open62541.c:223833:5: error: ‘RSA_size’ is deprecated: Since OpenSSL 3.0 **[-Werror=deprecated-declarations]**
223833 |     UA_Int32 keySize = RSA_size(get_pkey_rsa(privateKey));

open62541.c:223833:5: error: ‘EVP_PKEY_get0_RSA’ is deprecated: Since OpenSSL 3.0 **[-Werror=deprecated-declarations]**
223833 |     UA_Int32 keySize = RSA_size(get_pkey_rsa(privateKey));

error: ‘RSA_private_decrypt’ is deprecated: Since OpenSSL 3.0 **[-Werror=deprecated-declarations]**
223840 |         decryptedBytes = RSA_private_decrypt (keySize,

open62541.c:223843:28: error: ‘EVP_PKEY_get0_RSA’ is deprecated: Since OpenSSL 3.0 **[-Werror=deprecated-declarations]**
223843 |                            get_pkey_rsa(privateKey),      /* private key      */

open62541.c:223621:27: error: passing argument 4 of ‘RSA_private_decrypt’ discards ‘const’ qualifier from pointer target type **[-Werror=discarded-qualifiers]**
223621 | #define get_pkey_rsa(evp) EVP_PKEY_get0_RSA(evp)

/open62541.c:223904:5: error: ‘EVP_PKEY_get0_RSA’ is deprecated: Since OpenSSL 3.0 **[-Werror=deprecated-declarations]**
223904 |     rsa = get_pkey_rsa (evpPublicKey);

open62541.c:223904:9: error: assignment discards ‘const’ qualifier from pointer target type **[-Werror=discarded-qualifiers]**
223904 |     rsa = get_pkey_rsa (evpPublicKey);

open62541.c:223905:5: error: ‘RSA_size’ is deprecated: Since OpenSSL 3.0 **[-Werror=deprecated-declarations]**
223905 |     keySize = (size_t) RSA_size (rsa);

open62541.c:224065:5: error: ‘EVP_PKEY_get0_RSA’ is deprecated: Since OpenSSL 3.0 **[-Werror=deprecated-declarations]**
224065 |     RSA * rsa = get_pkey_rsa (evpKey);

open62541.c:223621:27: error: initialization discards ‘const’ qualifier from pointer target type **[-Werror=discarded-qualifiers]**
223621 | #define get_pkey_rsa(evp) EVP_PKEY_get0_RSA(evp)

open62541.c:224066:5: error: ‘RSA_size’ is deprecated: Since OpenSSL 3.0 **[-Werror=deprecated-declarations]**
224066 |     *keyLen = RSA_size(rsa);

open62541.c:224078:5: error: ‘RSA_size’ is deprecated: Since OpenSSL 3.0 **[-Werror=deprecated-declarations]**
224078 |     *keyLen = RSA_size(get_pkey_rsa(privateKey));

open62541.c:224078:5: error: ‘EVP_PKEY_get0_RSA’ is deprecated: Since OpenSSL 3.0 **[-Werror=deprecated-declarations]**
224078 |     *keyLen = RSA_size(get_pkey_rsa(privateKey));

open62541.c:227140:5: error: ‘RSA_new’ is deprecated: Since OpenSSL 3.0 **[-Werror=deprecated-declarations]**
227140 |     RSA *rsa = RSA_new();

open62541.c:227157:5: error: ‘RSA_generate_key_ex’ is deprecated: Since OpenSSL 3.0 **[-Werror=deprecated-declarations]**
227157 |     if(RSA_generate_key_ex(rsa, (int) keySizeBits, exponent, NULL) != 1) {

open62541.c:227164:5: error: ‘EVP_PKEY_assign’ is deprecated: Since OpenSSL 3.0 **[-Werror=deprecated-declarations]**
227164 |     if(EVP_PKEY_assign_RSA(pkey, rsa) != 1) {

open62541.c:227379:5: error: ‘RSA_free’ is deprecated: Since OpenSSL 3.0 **[-Werror=deprecated-declarations]**
227379 |     RSA_free(rsa);

cc1: note: unrecognized command-line option ‘-Wno-static-in-inline’ may have been intended to silence earlier diagnostics

cc1: all warnings being treated as errors

make[2]: *** [CMakeFiles/open62541-object.dir/build.make:285: CMakeFiles/open62541-object.dir/open62541.c.o] Error 1

make[1]: *** [CMakeFiles/Makefile2:423: CMakeFiles/open62541-object.dir/all] Error 2

make: *** [Makefile:136: all] Error 2

## Background Information / Reproduction Steps

Used CMake options:
# enable additional features

sudo apt-get install cmake-curses-gui              # for the ccmake graphical interface
sudo apt-get install libmbedtls-dev                  # for encryption support
sudo apt-get install check libsubunit-dev         # for unit tests
sudo apt-get install python-sphinx graphviz    # for documentation generation
sudo apt-get install python-sphinx-rtd-theme # documentation style

cd open62541
mkdir build
cd build
cmake ..
make

# select additional features
ccmake -DUA_ENABLE_AMALGAMATION=ON -DUA_ENABLE_ENCRYPTION=OPENSSL ..
make

## Checklist

Please provide the following information:

 - [ ] open62541 Version (release number or git tag): open62541 1.3.3.
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system: Ubuntu 22.04
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by danmoser** [comment]
Same problem here... open62541 1.3 and Ubuntu 22.04

**Comment by shaohuazhang1** [comment]
Have you resolved this problem?This issue occur on my linux both 22.04 and 20.04.

**Comment by shaohuazhang1** [comment]
openssl -v  openssl: /lib/x86_64-linux-gnu/libcrypto.so.3: version `OPENSSL_3.1.0' not found (required by openssl)

**Comment by danmoser** [comment]
@shaohuazhang1 , did you try `apt install openssl` on ubuntu 20.04? It worked for me. 
Alternatively, `apt install libmbedtls-dev` to use TLS library. That lib works on 22.04

**Comment by shaohuazhang1** [comment]
Compiled passed!
Tkank you!

**Comment by shaohuazhang1** [comment]
What configuration does the OPC server need after enable mbedtls?
configuration on the UAExpert 
security policy Basic128Rsa15
Message Security Mode Sign&Encrypt

**Comment by shaohuazhang1** [comment]
And when I compile with gcc -std=c99 open62541.c tutorial_pubsub_connection.c 
/usr/bin/ld: open62541.c:(.text+0x441052): undefined reference to `mbedtls_rsa_rsaes_oaep_encrypt'
/usr/bin/ld: /tmp/ccdNmZep.o: in function `mbedtls_decrypt_rsaOaep':
open62541.c:(.text+0x44114a): undefined reference to `mbedtls_rsa_set_padding'
/usr/bin/ld: open62541.c:(.text+0x4411f1): undefined reference to `mbedtls_ctr_drbg_random'
/usr/bin/ld: open62541.c:(.text+0x4411f9): undefined reference to `mbedtls_rsa_rsaes_oaep_decrypt'
/usr/bin/ld: /tmp/ccdNmZep.o: in function `UA_mbedTLS_LoadPrivateKey':
open62541.c:(.text+0x4412fe): undefined reference to `mbedtls_pk_parse_key'
/usr/bin/ld: /tmp/ccdNmZep.o: in function `UA_mbedTLS_LoadLocalCertificate':
open62541.c:(.text+0x44137e): undefined reference to `mbedtls_x509_crt_init'
/usr/bin/ld: open62541.c:(.text+0x44139e): undefined reference to `mbedtls_x509_crt_parse'
/usr/bin/ld: open62541.c:(.text+0x441421): undefined reference to `mbedtls_x509_crt_free'
collect2: error: ld returned 1 exit status

**Comment by danmoser** [comment]
@shaohuazhang1 , when compiling open62541 be sure that you have these options enabled: 
`cmake .. -DUA_ENABLE_ENCRYPTION=ON -DBUILD_SHARED_LIBS=ON -DMBEDTLS_INCLUDE_DIRS=/usr/include/mbedtls`

**Comment by jpfr** [comment]
@shaohuazhang1 Please verify and close with the current master.

**Comment by danmoser** [comment]
Folks, current master branch compiled here after `apt install libssl-dev openssl` on Ubuntu 22.04. 
Build option: `-DUA_ENABLE_ENCRYPTION=OPENSSL`
Thanks!!

**Comment by jpfr** [comment]
Nice! Closing.

**Comment by java-code-former** [comment]
so What is the solution？

**Comment by jpfr** [comment]
Use the master branch.
It has support for OpenSSL3.
