### ISSUE TITLE
Build Errors of pubsub_interrupt_publish.c

### ISSUE THREAD

**Issue by sarh2o** [open62541/open62541#3780]
## Description
Can't pass the building of pubsub_interrupt_publish.c
## Background Information / Reproduction Steps
1. following https://open62541.org/doc/current/building.html#building-the-library to build libopen62541.a
   I just run:

```sh
mkdir build
cd build
cmake ..
make
```

2. follow READMD.md under examples/pubsub_realtime. Set CMAKE_BUILD_TYPE to "Release" and below options to ON via ccmake ..
UA_ENABLE_PUBSUB
UA_ENABLE_PUBSUB_ETH_UADP
UA_ENABLE_PUBSUB_CUSTOM_PUBLISH_HANDLING
UA_ENABLE_MALLOC_SINGLETON
UA_ENABLE_IMMUTABLE_NODES
3. run
```sh
cmake ..
make
```
4. follow  READMD.md under examples/pubsub_realtime. run
```sh
gcc -O2 ../examples/pubsub_realtime/pubsub_interrupt_publish.c ../examples/pubsub_realtime/bufmalloc.c -I../include -I../plugins/include -Isrc_generated -I../arch/posix -I../arch -I../plugins/networking bin/libopen62541.a -lrt -o rt_publisher
```
I got below error:
In file included from ../include/open62541/server.h:28,
                 from ../examples/pubsub_realtime/pubsub_interrupt_publish.c:12:
../include/open62541/plugin/nodestore.h:21:10: fatal error: ziptree.h: No such file or directory
   21 | #include "ziptree.h"
5. I added -I../deps into the build command and run again
```sh
gcc -O2 ../examples/pubsub_realtime/pubsub_interrupt_publish.c ../examples/pubsub_realtime/bufmalloc.c -I../include -I../plugins/include -Isrc_generated -I../arch/posix -I../arch -I../plugins/networking -I../deps bin/libopen62541.a -lrt -o rt_publisher
```
and got errors:
../examples/pubsub_realtime/pubsub_interrupt_publish.c: In function ‘addPubSubConfiguration’:
../examples/pubsub_realtime/pubsub_interrupt_publish.c:290:32: error: ‘UA_DataSetVariableConfig’ {aka ‘struct <anonymous>’} has no member named ‘staticValueSourceEnabled’
  290 |     counterValue.field.variable.staticValueSourceEnabled = true;
      |                                ^
../examples/pubsub_realtime/pubsub_interrupt_publish.c:291:52: error: ‘UA_DataSetVariableConfig’ {aka ‘struct <anonymous>’} has no member named ‘staticValueSource’; did you mean ‘rtValueSource’?
  291 |     UA_DataValue_init(&counterValue.field.variable.staticValueSource);
      |                                                    ^~~~~~~~~~~~~~~~~
      |                                                    rtValueSource
../examples/pubsub_realtime/pubsub_interrupt_publish.c:292:55: error: ‘UA_DataSetVariableConfig’ {aka ‘struct <anonymous>’} has no member named ‘staticValueSource’; did you mean ‘rtValueSource’?
  292 |     UA_Variant_setScalar(&counterValue.field.variable.staticValueSource.value,
      |                                                       ^~~~~~~~~~~~~~~~~
      |                                                       rtValueSource
../examples/pubsub_realtime/pubsub_interrupt_publish.c:294:33: error: ‘UA_DataSetVariableConfig’ {aka ‘struct <anonymous>’} has no member named ‘staticValueSource’; did you mean ‘rtValueSource’?
  294 |     counterValue.field.variable.staticValueSource.value.storageType = UA_VARIANT_DATA_NODELETE;
      |                                 ^~~~~~~~~~~~~~~~~
      |                                 rtValueSource

I've no idea how to handle this error.

Used CMake options:

CMAKE_BUILD_TYPE = Release
UA_ENABLE_PUBSUB
UA_ENABLE_PUBSUB_ETH_UADP
UA_ENABLE_PUBSUB_CUSTOM_PUBLISH_HANDLING
UA_ENABLE_MALLOC_SINGLETON
UA_ENABLE_IMMUTABLE_NODES

```bash
cmake -DUA_NAMESPACE_ZERO=<YOUR_OPTION> <ANY_OTHER_OPTIONS> ..
```

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): branch: master commit: c749a17e2647f68bdad070fa840f62a12d05f9e3
 - [x] Other OPC UA SDKs used (client or server): No
 - [x] Operating system:ubuntu 20.04
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by sarh2o** [comment]
As per my investigation, this issue is caused by commit: 0e520fe20f58d52c032e28903cd91fd97cc5ec17

feat(core/pubsub) External Data Source and Information model RT varia…

…bles (#3739)

Extended/refactor the node value source structure to the new data source value backend concept, added the sceleton for a PubSub RT example with information model related nodes

It seems that there was a refactor feature which changed the definition of structure UA_DataSetVariableConfig in server_pubsub.h. But pubsub_interrupt_publish.c was not updated accordingly.

Thanks!

**Comment by sarh2o** [comment]
I changes my local code as below. Then it can pass the building. But I'm not sure whether it is the official way to adapt the code.

Thanks!

```git
git diff
diff --git a/examples/pubsub_realtime/pubsub_interrupt_publish.c b/examples/pubsub_realtime/pubsub_interrupt_publish.c
index c5d30ef9..87bb3277 100644
--- a/examples/pubsub_realtime/pubsub_interrupt_publish.c
+++ b/examples/pubsub_realtime/pubsub_interrupt_publish.c
@@ -287,11 +287,10 @@ addPubSubConfiguration(UA_Server* server) {
     counterValue.field.variable.publishParameters.attributeId = UA_ATTRIBUTEID_VALUE;
 
 #if (PUBSUB_RT_LEVEL == UA_PUBSUB_RT_FIXED_SIZE) || (PUBSUB_RT_LEVEL == UA_PUBSUB_RT_DIRECT_VALUE_ACCESS)
-    counterValue.field.variable.staticValueSourceEnabled = true;
-    UA_DataValue_init(&counterValue.field.variable.staticValueSource);
-    UA_Variant_setScalar(&counterValue.field.variable.staticValueSource.value,
-                         &publishValue, &UA_TYPES[UA_TYPES_UINT64]);
-    counterValue.field.variable.staticValueSource.value.storageType = UA_VARIANT_DATA_NODELETE;
+    UA_DataValue *staticValueSource = UA_DataValue_new();
+    UA_Variant_setScalar(&staticValueSource->value, &publishValue, &UA_TYPES[UA_TYPES_UINT64]);
+    counterValue.field.variable.rtValueSource.rtFieldSourceEnabled = UA_TRUE;
+    counterValue.field.variable.rtValueSource.staticValueSource = &staticValueSource;
 #endif
     UA_Server_addDataSetField(server, publishedDataSetIdent, &counterValue,
                               &dataSetFieldIdentCounter);
```
